# Numpy

In [2]:
#The NumPy library is the core library for scientific computing in Python. 
#It provides a high-performance multidimensional
#Array object, and tools for working with these arrays. 

In [4]:
#How to install Numpy 
#!pip install numpy
#How to find the version of Numpy
import numpy as np
np.version.version

'1.16.5'

In [5]:
# Python Numpy Array is better then List because:
# -->Less Memory
# -->Fast(Speed)
# -->Convenient

In [12]:
# Memory allocation
import numpy as np
 
import time
import sys
S= range(1000)
print("Memory allocation by List")
print(sys.getsizeof(5)*len(S))
 
D= np.arange(1000)
print("Memory allocation by Array")
print(D.size*D.itemsize)

Memory allocation by List
28000
Memory allocation by Array
4000


In [13]:
# Faster and convenient

import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print("Time taken by List")
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print("Time taken by Array")
print((time.time()-start)*1000)

Time taken by List
184.47542190551758
Time taken by Array
49.8652458190918


# numpy.dtype

In [15]:
# Numpy supports vide varity of numeric types
import numpy as np
GP = np.array([[79,62,76,77,69,76,74,82,55,51]])
print(GP.dtype)

int32


# np.ndim

In [21]:
#Find the dimension of an array
import numpy as np
GP = np.array([(1,2,3),(4,5,6)])
print(GP.ndim)
GP

2


array([[1, 2, 3],
       [4, 5, 6]])

# np.itemsize

In [19]:
# itemsize-calculate the byte size of each element.
import numpy as np
GP = np.array([[79,62,76,77,69,76,74,82,55,51]],dtype=np.int8)
print(GP.itemsize)

1


In [20]:
import numpy as np
GP = np.array([[79,62,76,77,69,76,74,82,55,51]],dtype=np.float32)
print(GP.itemsize)

4


# np.shape

In [23]:
# shape-returns shape of the array in the form of rows and column
import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],[82,66,82,46,67,80,81,80,73,45]]) 
print( GP.shape)

(4, 10)


In [22]:
# shape function-returns shape of the array in the form of rows and column

import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51],[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48], [0,0,82,82,82,75,75,73,80,54],[82,66,80,80,67,35,61,85,75,18],
              [61,66,79,80,6,81,75,79,77,34]]) 
print( GP.shape)


(10, 10)


In [24]:
# using shape function to resize the array
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.shape)
print(a)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
a.shape=(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [26]:
# Also used to resize the array

import numpy as np 

GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51],[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48]
              ]) 
print(GP.shape)

(7, 10)


In [27]:
print("Resize the array")
GP.shape = (10,7) 
print (GP)

Resize the array
[[79 62 76 77 69 76 74]
 [82 55 51 74 26 78 78]
 [80 79 79 51 69  4 78]
 [66 81 81 27 72 62 78]
 [78  0 82 66 82 46 67]
 [80 81 80 73 45 82 62]
 [78 73 81 82 81 72 78]
 [51 80 60 70 62 82 74]
 [61 58 58 54  0  0  0]
 [77 81 80 80 75 72 48]]


In [28]:
print(GP.shape)

(10, 7)


In [29]:
GP

array([[79, 62, 76, 77, 69, 76, 74],
       [82, 55, 51, 74, 26, 78, 78],
       [80, 79, 79, 51, 69,  4, 78],
       [66, 81, 81, 27, 72, 62, 78],
       [78,  0, 82, 66, 82, 46, 67],
       [80, 81, 80, 73, 45, 82, 62],
       [78, 73, 81, 82, 81, 72, 78],
       [51, 80, 60, 70, 62, 82, 74],
       [61, 58, 58, 54,  0,  0,  0],
       [77, 81, 80, 80, 75, 72, 48]])

# np.reshape

In [30]:
# Also provide reshape function to resize the array

import numpy as np 
a = np.array([[[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51],[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48]]])
print(a)

print('After reshaping')
b = a.reshape(10,7) 
print (b)

[[[79 62 76 77 69 76 74 82 55 51]
  [74 26 78 78 80 79 79 51 69  4]
  [78 66 81 81 27 72 62 78 78  0]
  [82 66 82 46 67 80 81 80 73 45]
  [82 62 78 73 81 82 81 72 78 51]
  [80 60 70 62 82 74 61 58 58 54]
  [ 0  0  0 77 81 80 80 75 72 48]]]
After reshaping
[[79 62 76 77 69 76 74]
 [82 55 51 74 26 78 78]
 [80 79 79 51 69  4 78]
 [66 81 81 27 72 62 78]
 [78  0 82 66 82 46 67]
 [80 81 80 73 45 82 62]
 [78 73 81 82 81 72 78]
 [51 80 60 70 62 82 74]
 [61 58 58 54  0  0  0]
 [77 81 80 80 75 72 48]]


# np.empty

In [31]:
# empty function-used to create an uninitializd array of specified shape and size
# numpy.empty(shape, dtype = float, order = 'C'

import numpy as np
a=np.empty([3,2])     # where(3,2) defines the shape of array
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# np.zero

In [33]:
# zeros function-returns an array filled with zero depends on its size
# numpy.zeros(shape, dtype = float, order = 'C')

import numpy as np
a=np.zeros([3,2])
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
import numpy as np
a=np.zeros([3,2],dtype=np.int)
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [35]:
import numpy as np
a=np.zeros([3,2],dtype=np.float)
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# np.ones

In [36]:
# ones function-returns an array filled with one depends on its size and data type
# numpy.ones(shape, dtype = None, order = 'C')

import numpy as np
a=np.ones([3,2])
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [37]:
import numpy as np
a=np.ones([3,3],dtype=np.int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# np.arange

In [38]:
# arange function

import numpy as np 
x = np.arange(5) 
print (x)

[0 1 2 3 4]


In [39]:
import numpy as np 
x = np.arange(5,dtype=np.float) 
print (x)

[0. 1. 2. 3. 4.]


In [41]:
# arange function-Creating an array of evenly spaced value(step value)
# numpy.arange(start, stop, step, dtype)

import numpy as np 
x = np.arange(10,25,5)    # start=10,stop=25,step=5 
print (x)

[10 15 20]


In [42]:
import numpy as np 
x = np.arange(10,25,5,dtype=np.float) 
print (x)

[10. 15. 20.]


# Indexing and Slicing

In [43]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print (a[s])

[2 4 6]


In [44]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [45]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
print (b)

5


In [46]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [47]:
# slice items between indexes 

import numpy as np 
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [48]:
# print the elements from index 3 to 7
import numpy as np
GP=np.array([79,62,76,77,69,76,74,82,55,51])

print(GP[3:8])

[77 69 76 74 82]


In [49]:
#Basketball Game
# Games Played
LeBronJames_G = [79,62,76,77,69,76,74,82,55,51]
StephenCurry_G = [74,26,78,78,80,79,79,51,69,4]
KevinDurant_G = [78,66,81,81,27,72,62,78,78,0]
RusselWestBrook_G = [82,66,82,46,67,80,81,80,73,45]
JamesHarden_G = [82,62,78,73,81,82,81,72,78,51]
ChrisPaul_G = [80,60,70,62,82,74,61,58,58,54]
GiannisAntetokounmpo_G = [0,0,0,77,81,80,80,75,72,48]
DamianLillard_G = [0,0,82,82,82,75,75,73,80,54]
BlakeGriffin_G = [82,66,80,80,67,35,61,85,75,18]
PaulGeorgee_G = [61,66,79,80,6,81,75,79,77,34]

In [50]:

# If a : is inserted in front of single parameter, all items from that index onwards will be extracted.

import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]]) 
print (GP)  


# slice items starting from index
print()
print ('Now we will slice the array from the index a[1:]') 
print (GP[1:])

[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]]

Now we will slice the array from the index a[1:]
[[74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]]


In [57]:
#Integer Indexing
# Each element of first dimension is paired with the element of the second dimension. 
# So the index of the elements in this case are (0,0),(1,0),(2,1) and the corresponding elements are selected.

 
import numpy as np 
  
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]]) 
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


In [52]:
import numpy as np 
  
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]]) 
print(GP[[0 ,1 ,2 ],[3 ,5 ,8]])

[77 79 78]


In [53]:
import numpy as np 

GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]]) 
print(GP[[0,1,2], [6,1,9]]) 


[74 26  0]


In [54]:

import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]
              ,[82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51]]) 
   
print ('Our array is:' )
print (GP) 
print ('\n') 

rows = np.array([[0,0],[4,4]])   # it seems confusing so here take row 0 col 0 =79 , rows 0 cols 9= 82
cols = np.array([[0,9],[0,9]])   #  row 4 cols 0 = 51  and  rows 4  cols 9= 51   match them vertically
 
   
print ('The corner elements of this array are:') 
print (GP[rows,cols])

Our array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]]


The corner elements of this array are:
[[79 51]
 [82 51]]


In [55]:
import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]
              ,[82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51]]) 

print ('Our array is:') 
print (GP) 
print ('\n' ) 

# slicing 
z = GP[1:5,1:4] 

print ('After slicing, our array becomes:') 
print (z) 
print ('\n')  

# using advanced index for column 
y = GP[1:5,[1,2,3]] 

print ('Slicing using advanced index for column:') 
print (y)

Our array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]]


After slicing, our array becomes:
[[26 78 78]
 [66 81 81]
 [66 82 46]
 [62 78 73]]


Slicing using advanced index for column:
[[26 78 78]
 [66 81 81]
 [66 82 46]
 [62 78 73]]


In [56]:
#Boolean Indexing
# You may wish to select numbers greater than 50 
import numpy as np 
  
a = np.array([10, 40, 80, 50, 100]) 
print(a[a>50]) 

[ 80 100]


In [60]:

  
import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51],[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48], [0,0,82,82,82,75,75,73,80,54],[82,66,80,80,67,35,61,85,75,18],
              [61,66,79,80,6,81,75,79,77,34]]) 

print ('Our array is:' )
print (GP) 
print ('\n') 

print('Games played more then 82')
print(GP[GP>82])

Our array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]
 [80 60 70 62 82 74 61 58 58 54]
 [ 0  0  0 77 81 80 80 75 72 48]
 [ 0  0 82 82 82 75 75 73 80 54]
 [82 66 80 80 67 35 61 85 75 18]
 [61 66 79 80  6 81 75 79 77 34]]


Games played more then 82
[85]


In [61]:
# You may wish to square the multiples of 40  
import numpy as np 
  
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51],[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48], [0,0,82,82,82,75,75,73,80,54],[82,66,80,80,67,35,61,85,75,18],
              [61,66,79,80,6,81,75,79,77,34]])  
print(GP[GP%25==0]**2) 

[   0    0    0    0 5625    0    0 5625 5625 5625 5625]


In [62]:
#Broadcasting
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [63]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a) 
print ('\n')  
   
print ('Second array:') 
print (b) 
print ('\n')  
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [64]:
#Iteration
# numpy.nditer

import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
   print (x),

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [65]:
# numpy.nditer
import numpy as np
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]]) 

print ('Original array is:')
print (GP)
print ('\n')

print ('Modified array is:')
for x in np.nditer(GP):
   print (x),

Original array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]]


Modified array is:
79
62
76
77
69
76
74
82
55
51
74
26
78
78
80
79
79
51
69
4
78
66
81
81
27
72
62
78
78
0


In [66]:
import numpy as np
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]]) 

print ('Original array is:')
print (GP)
print ('\n')
print ('Transpose of the original array is:') 
b = GP.T 
print (b) 
print ('\n')  
   
print ('Modified array is:') 
for x in np.nditer(b): 
   print (x),

Original array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]]


Transpose of the original array is:
[[79 74 78]
 [62 26 66]
 [76 78 81]
 [77 78 81]
 [69 80 27]
 [76 79 72]
 [74 79 62]
 [82 51 78]
 [55 69 78]
 [51  4  0]]


Modified array is:
79
62
76
77
69
76
74
82
55
51
74
26
78
78
80
79
79
51
69
4
78
66
81
81
27
72
62
78
78
0


In [67]:
# numpy.transpose(arr, axes)


import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51],[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48], [0,0,82,82,82,75,75,73,80,54],[82,66,80,80,67,35,61,85,75,18],
              [61,66,79,80,6,81,75,79,77,34]]) 

print ('The original array is:') 
print (GP)  
print ('\n') 

print ('The transposed array is:') 
print (np.transpose(GP))


The original array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]
 [80 60 70 62 82 74 61 58 58 54]
 [ 0  0  0 77 81 80 80 75 72 48]
 [ 0  0 82 82 82 75 75 73 80 54]
 [82 66 80 80 67 35 61 85 75 18]
 [61 66 79 80  6 81 75 79 77 34]]


The transposed array is:
[[79 74 78 82 82 80  0  0 82 61]
 [62 26 66 66 62 60  0  0 66 66]
 [76 78 81 82 78 70  0 82 80 79]
 [77 78 81 46 73 62 77 82 80 80]
 [69 80 27 67 81 82 81 82 67  6]
 [76 79 72 80 82 74 80 75 35 81]
 [74 79 62 81 81 61 80 75 61 75]
 [82 51 78 80 72 58 75 73 85 79]
 [55 69 78 73 78 58 72 80 75 77]
 [51  4  0 45 51 54 48 54 18 34]]


In [68]:
# behave similar to np.transpose


import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51],[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48], [0,0,82,82,82,75,75,73,80,54],[82,66,80,80,67,35,61,85,75,18],
              [61,66,79,80,6,81,75,79,77,34]]) 

print ('The original array is:') 
print (GP)  
print ('\n') 

print ('The transposed array is:') 
print (GP.T)

The original array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]
 [80 60 70 62 82 74 61 58 58 54]
 [ 0  0  0 77 81 80 80 75 72 48]
 [ 0  0 82 82 82 75 75 73 80 54]
 [82 66 80 80 67 35 61 85 75 18]
 [61 66 79 80  6 81 75 79 77 34]]


The transposed array is:
[[79 74 78 82 82 80  0  0 82 61]
 [62 26 66 66 62 60  0  0 66 66]
 [76 78 81 82 78 70  0 82 80 79]
 [77 78 81 46 73 62 77 82 80 80]
 [69 80 27 67 81 82 81 82 67  6]
 [76 79 72 80 82 74 80 75 35 81]
 [74 79 62 81 81 61 80 75 61 75]
 [82 51 78 80 72 58 75 73 85 79]
 [55 69 78 73 78 58 72 80 75 77]
 [51  4  0 45 51 54 48 54 18 34]]


In [69]:
#Joining Array 
#Concatenation Function 

# numpy.concatenate((a1, a2, ...), axis)


import numpy as np 
# First Array
GP1 = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51]]) 
print ('First array:') 
print (GP1) 
print ('\n')


# Second Array
GP2 = np.array([[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48], [0,0,82,82,82,75,75,73,80,54],[82,66,80,80,67,35,61,85,75,18],
              [61,66,79,80,6,81,75,79,77,34]]) 
print ('Second array:') 
print (GP2) 
print ('\n')


First array:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]]


Second array:
[[80 60 70 62 82 74 61 58 58 54]
 [ 0  0  0 77 81 80 80 75 72 48]
 [ 0  0 82 82 82 75 75 73 80 54]
 [82 66 80 80 67 35 61 85 75 18]
 [61 66 79 80  6 81 75 79 77 34]]




In [70]:
# both the arrays are of same dimensions 

print ('Joining the two arrays along axis 0:') 
print (np.concatenate((GP1,GP2))) 
print ('\n')  

Joining the two arrays along axis 0:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]
 [80 60 70 62 82 74 61 58 58 54]
 [ 0  0  0 77 81 80 80 75 72 48]
 [ 0  0 82 82 82 75 75 73 80 54]
 [82 66 80 80 67 35 61 85 75 18]
 [61 66 79 80  6 81 75 79 77 34]]




In [71]:
print ('Joining the two arrays along axis 1:') 
print (np.concatenate((GP1,GP2),axis = 1))

Joining the two arrays along axis 1:
[[79 62 76 77 69 76 74 82 55 51 80 60 70 62 82 74 61 58 58 54]
 [74 26 78 78 80 79 79 51 69  4  0  0  0 77 81 80 80 75 72 48]
 [78 66 81 81 27 72 62 78 78  0  0  0 82 82 82 75 75 73 80 54]
 [82 66 82 46 67 80 81 80 73 45 82 66 80 80 67 35 61 85 75 18]
 [82 62 78 73 81 82 81 72 78 51 61 66 79 80  6 81 75 79 77 34]]


In [72]:
#Arithmatic Operations 

In [73]:
# Basic Airthmeic Operations

import numpy as np 
GP1 = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51]]) 
print ('First array:') 
print (GP1) 
print ('\n')  

print ('Second array:') 
GP2 = np.array([[80,60,70,62,82,74,61,58,58,54],
              [0,0,0,77,81,80,80,75,72,48], [0,0,82,82,82,75,75,73,80,54],[82,66,80,80,67,35,61,85,75,18],
              [61,66,79,80,6,81,75,79,77,34]]) 
print (GP2) 
print ('\n')  

First array:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]]


Second array:
[[80 60 70 62 82 74 61 58 58 54]
 [ 0  0  0 77 81 80 80 75 72 48]
 [ 0  0 82 82 82 75 75 73 80 54]
 [82 66 80 80 67 35 61 85 75 18]
 [61 66 79 80  6 81 75 79 77 34]]




In [74]:
# add()

print ('Add the two arrays:') 
print (np.add(GP1,GP2)) 
print ('\n')

Add the two arrays:
[[159 122 146 139 151 150 135 140 113 105]
 [ 74  26  78 155 161 159 159 126 141  52]
 [ 78  66 163 163 109 147 137 151 158  54]
 [164 132 162 126 134 115 142 165 148  63]
 [143 128 157 153  87 163 156 151 155  85]]




In [76]:
# subtract()

print ('Subtract the two arrays:') 
print (np.subtract(GP1,GP2)) 
print ('\n')

Subtract the two arrays:
[[ -1   2   6  15 -13   2  13  24  -3  -3]
 [ 74  26  78   1  -1  -1  -1 -24  -3 -44]
 [ 78  66  -1  -1 -55  -3 -13   5  -2 -54]
 [  0   0   2 -34   0  45  20  -5  -2  27]
 [ 21  -4  -1  -7  75   1   6  -7   1  17]]




In [77]:
# multiply()

print ('Multiply the two arrays:') 
print (np.multiply(GP1,GP2)) 
print ('\n')  


Multiply the two arrays:
[[6320 3720 5320 4774 5658 5624 4514 4756 3190 2754]
 [   0    0    0 6006 6480 6320 6320 3825 4968  192]
 [   0    0 6642 6642 2214 5400 4650 5694 6240    0]
 [6724 4356 6560 3680 4489 2800 4941 6800 5475  810]
 [5002 4092 6162 5840  486 6642 6075 5688 6006 1734]]




In [78]:
# divide()
print ('Divide the two arrays:') 
print (np.divide(GP1,GP2))

Divide the two arrays:
[[ 0.9875      1.03333333  1.08571429  1.24193548  0.84146341  1.02702703
   1.21311475  1.4137931   0.94827586  0.94444444]
 [        inf         inf         inf  1.01298701  0.98765432  0.9875
   0.9875      0.68        0.95833333  0.08333333]
 [        inf         inf  0.98780488  0.98780488  0.32926829  0.96
   0.82666667  1.06849315  0.975       0.        ]
 [ 1.          1.          1.025       0.575       1.          2.28571429
   1.32786885  0.94117647  0.97333333  2.5       ]
 [ 1.3442623   0.93939394  0.98734177  0.9125     13.5         1.01234568
   1.08        0.91139241  1.01298701  1.5       ]]


C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [79]:
#Power
# power()-

import numpy as np 
a = np.array([10,100,1000]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying power function:') 
print (np.power(a,2)) 
print ('\n')  

print ('Second array:') 
b = (np.array([1,2,3])) 
print (b) 
print ('\n')  

print ('Applying power function again:') 
print (np.power(a,b))

Our array is:
[  10  100 1000]


Applying power function:
[    100   10000 1000000]


Second array:
[1 2 3]


Applying power function again:
[        10      10000 1000000000]


In [80]:
import numpy as np 
GP = np.array([79,62,76,77,69,76,74,82,55,51]) 

print ('Our array is:') 
print (GP) 
print ('\n')  

print ('Applying power function:') 
print (np.power(GP,3)) 
print ('\n')  



Our array is:
[79 62 76 77 69 76 74 82 55 51]


Applying power function:
[493039 238328 438976 456533 328509 438976 405224 551368 166375 132651]




In [81]:
#Mod function
# mod()

import numpy as np 
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Second array:') 
print (b) 
print ('\n')  

print ('Applying mod() function:') 
print (np.mod(a,b)) 
print ('\n')  

print ('Applying remainder() function:') 
print (np.remainder(a,b)) 

First array:
[10 20 30]


Second array:
[3 5 7]


Applying mod() function:
[1 0 2]


Applying remainder() function:
[1 0 2]


In [82]:
#Statistical function 
# These functions return the minimum and the maximum from the elements in the given array along the specified axis.

import numpy as np 
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]]) 

print ('Our array is:') 
print (GP)  
print ('\n')  

print ('Using amin() function:') 
print (np.amin(GP,1)) 
print ('\n')  

print ('Using amin() function again:') 
print (np.amin(GP,0)) 
print ('\n')  


Our array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]]


Using amin() function:
[51  4  0]


Using amin() function again:
[74 26 76 77 27 72 62 51 55  0]




In [83]:

print ('Using amax() function:') 
print (np.amax(GP)) 
print ('\n')  

print ('Using amax() function again:') 
print (np.amax(GP, axis = 0))

Using amax() function:
82


Using amax() function again:
[79 66 81 81 80 79 79 82 78 51]


In [84]:
#Percentile
# numpy.percentile(a, q, axis) q-The percentile to compute must be between 0-100
#  It is a measure used in statistics indicating the value below which a given percentage of observations in a group of 
# observations fall.

import numpy as np 
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying percentile() function:') 
print (np.percentile(a,50)) 
print ('\n')  

print ('Applying percentile() function along axis 1:') 
print (np.percentile(a,50, axis = 1)) 
print ('\n')  

print ('Applying percentile() function along axis 0:') 
print (np.percentile(a,50, axis = 0))

Our array is:
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying percentile() function:
50.0


Applying percentile() function along axis 1:
[40. 20. 60.]


Applying percentile() function along axis 0:
[50. 40. 60.]


In [85]:
# Median is defined as the value separating the higher half of a data sample from the lower half. 


import numpy as np 
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying median() function:') 
print (np.median(a)) 
print ('\n')  

print ('Applying median() function along axis 0:') 
print (np.median(a, axis = 0)) 
print ('\n')  
 
print ('Applying median() function along axis 1:') 
print (np.median(a, axis = 1))

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


Applying median() function:
65.0


Applying median() function along axis 0:
[50. 90. 60.]


Applying median() function along axis 1:
[65. 80. 60.]


In [87]:
# Arithmetic mean is the sum of elements along an axis divided by the number of elements. 
# The numpy.mean() function returns the arithmetic mean of elements in the array.
# If the axis is mentioned, it is calculated along it.



import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print ('Our array is:') 
print (a) 
print ('\n')  

print ('Applying mean() function:') 
print (np.mean(a)) 
print ('\n')  

print ('Applying mean() function along axis 0:') 
print (np.mean(a, axis = 0)) 
print ('\n')  

print ('Applying mean() function along axis 1:')
print (np.mean(a, axis = 1)) 

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function:
3.6666666666666665


Applying mean() function along axis 0:
[2.66666667 3.66666667 4.66666667]


Applying mean() function along axis 1:
[2. 4. 5.]


In [88]:
# is the square root of the average of squared deviations from mean.
# std = sqrt(mean(abs(x - x.mean())**2))

import numpy as np 
print (np.std([79,62,76,77,69,76,74,82,55,51]))

10.06429331846007


In [89]:
#  is the average of squared deviations, i.e., mean(abs(x - x.mean())**2).

import numpy as np 
print (np.var([79,62,76,77,69,76,74,82,55,51]))

101.28999999999999


In [90]:
# numpy.sort(a, axis, kind, order)
# The sort() function returns a sorted copy of the input array.

import numpy as np  
GP = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0],
              [82,66,82,46,67,80,81,80,73,45],[82,62,78,73,81,82,81,72,78,51]]) 

print ('Our array is:') 
print (GP) 
print ('\n')

print ('Applying sort() function:') 
print (np.sort(GP)) 
print ('\n') 
  
print ('Sort along axis 0:') 
print (np.sort(GP, axis = 0)) 
print ('\n')  



Our array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]
 [82 66 82 46 67 80 81 80 73 45]
 [82 62 78 73 81 82 81 72 78 51]]


Applying sort() function:
[[51 55 62 69 74 76 76 77 79 82]
 [ 4 26 51 69 74 78 78 79 79 80]
 [ 0 27 62 66 72 78 78 78 81 81]
 [45 46 66 67 73 80 80 81 82 82]
 [51 62 72 73 78 78 81 81 82 82]]


Sort along axis 0:
[[74 26 76 46 27 72 62 51 55  0]
 [78 62 78 73 67 76 74 72 69  4]
 [79 62 78 77 69 79 79 78 73 45]
 [82 66 81 78 80 80 81 80 78 51]
 [82 66 82 81 81 82 81 82 78 51]]




In [91]:
#Where function 
# The where() function returns the indices of elements in an input array where the given condition is satisfied.

import numpy as np 
x = np.arange(9.).reshape(3, 3) 

print ('Our array is:') 
print (x)  

print ('Indices of elements > 3') 
y = np.where(x > 3) 
print (y)  

print ('Use these indices to get elements satisfying the condition') 
print (x[y])

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Indices of elements > 3
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
Use these indices to get elements satisfying the condition
[4. 5. 6. 7. 8.]


In [92]:

import numpy as np 
x = np.array([[79,62,76,77,69,76,74,82,55,51],[74,26,78,78,80,79,79,51,69,4],[78,66,81,81,27,72,62,78,78,0]])

print ('Our array is:') 
print (x)  

print ('Indices of elements > 75') 
y = np.where(x > 75) 
print (y)  

print ('Use these indices to get elements satisfying the condition') 
print (x[y])

Our array is:
[[79 62 76 77 69 76 74 82 55 51]
 [74 26 78 78 80 79 79 51 69  4]
 [78 66 81 81 27 72 62 78 78  0]]
Indices of elements > 75
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=int64), array([0, 2, 3, 5, 7, 2, 3, 4, 5, 6, 0, 2, 3, 7, 8], dtype=int64))
Use these indices to get elements satisfying the condition
[79 76 77 76 82 78 78 80 79 79 78 81 81 78 78]


In [93]:
# The extract() function returns the elements satisfying any condition.

import numpy as np 
x = np.arange(9.).reshape(3, 3) 

print ('Our array is:') 
print (x)  

# define a condition 
condition = np.mod(x,2) == 0 

print ('Element-wise value of condition') 
print (condition)  

print ('Extract elements using condition') 
print (np.extract(condition, x))

Our array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Element-wise value of condition
[[ True False  True]
 [False  True False]
 [ True False  True]]
Extract elements using condition
[0. 2. 4. 6. 8.]
